services:
  test_frontend_service:
    build: 
      context: .
      args:
        - HOST_IP=${HOST_IP}
        - COMMAND_PORT=${COMMAND_PORT}
        - QUERY_PORT=${QUERY_PORT}
    container_name: test_react_mui_cqrs
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: package.json
          action: rebuild
    env_file:
      - ../env.properties
    ports:
    - "80:3000"
